# For more see https://gohugo.io/content-management/menus/

main:                # sections in the website sidebar
  - identifier: home # section id
    name: Home       # section display title
    url: /           # path to the section
    weight: 1        # order of sections

  - identifier: readinglist
    name: Reading List
    url: /reading_list/
    weight: 2

  - identifier: listeninglog
    name: Listening Log
    url: /listening_log/
    weight: 3

  - identifier: writing
    name: Writing
    url: /writing/
    weight: 4

  - identifier: code
    name: Code
    url: https://www.github.com/mondayrain
    weight: 5
