# Site description. Used in meta description
description: >-
  stuff you can peruse

# SEO keywords. Used in 'meta name="keywords"' tag.
# May be overridden by .Keywords or .Tags in front matter.
keywords:
  - larissa feng
  - software developer
  - vancouver
  - toronto

# A "copyright"-line to be added to RSS/Atom files.
# "&copy;" and "{year}" will be replaced by © and the current year.
copyright: '2022 Larissa Feng'

# Colour scheme. Options: red, orange, magenta, cyan, blue, brown
colorScheme: ''

# Used in site header
tagline: Software Developer | Cloud Infrastructure

# Custom footer text on left sidebar. Use HTMl if needed.
# "&copy;" and "{year}" will be replaced by © and the current year.
footer: >-
  <div style="text-align: center"><a href="https://www.github.com/mondayrain/" target="_blank">Github</a> | <a href="https://www.linkedin.com/in/larissafeng/" target="_blank">LinkedIn</a> | <a href="mailto:hello@larissafeng.me">Email</a></div>

# Sections to be displayed in:
# - main page
# - RSS/Atom/Json feeds
# - search index
# - ...
mainSections:
  - listeninglog
  - readinglist
  - writing

# Posts date format, for example: 2006-01-02
dateFormat: ':date_long'
dateFormatToc: 2006.01.02

# Show "Read more" button in list if true
readmore: true

# RSS/Atom feed size
feedSize: 25

recentPostsSize: 5

contact:
  # Forms Backend URL, used in contacts form
  formAction: 'https://submit-form.com/example'

  # Contact form email subject
  emailSubject: Contact form submission

  # Where should the user be redirected after successful form submit?
  thanksUrl: /thanks

# Site icons, relative to ./static
assets:
  # favicon.ico for legacy browsers
  favicon: ''

  # A single SVG icon with a light/dark version for modern browsers
  svgicon: ''

  # 180×180 PNG image for Apple devices
  apple_touch_icon: ''

  # Logo image, relative to ./assets
  logo: /img/open-graph-logo.png
  disable_fingerprinting: false

seo:
  # Will be used in schema.org/Organization.
  # The site.Title  will be used if empty.
  publisher: Larissa Feng

  # To anonymize the IP addresses of hits sent to Google Analytics
  # set this param to true. Please note, to enable Google Analytics
  # you have to set `googleAnalytics` param in config.yaml file.
  anonymizeIp: true

social:
  # Array of Facebook Page Admin IDs for Domain Insights
  facebookAdminIds: []

  # Facebook Page ID
  facebookId: ''

  # Twitter username for the website
  twitter: larissafeng

# # Configure search engine
# search:
#   # Maximum length (in words) of each text blurb. You can change this
#   # value if you find that 100 is too short or too long for your taste.
#   maxSummaryLength: 100
#   # Lunr has full support for the indexing and searching of documents
#   # in English. If your documents are in another language, uncomment
#   # required languages below.
#   #
#   # For more see: https://lunrjs.com/guides/language_support.html
#   languages:
#     # - de
#     - en
#     # - fr
#     # - it
#     # - pt
#     # - ru
