title = "Larissa Feng"
tagline = "another developer with a website"
description = "Software Developer, hobbyist musician, writer/reader Larissa Feng."
url = "https://larissafeng.me"
baseurl = "https://larissafeng.me"
permalink = "/:title/"
encoding = "utf-8"
markdown = "kramdown"
exclude = [ "optional", "vendor" ]
theme = "ed"

[author]
name = "Larissa Feng"
url = "https://larissafeng.me"
email = "hello@larissafeng.me"

[collections.texts]
output = true

[kramdown]
auto_ids = true
footnote_nr = 1
entity_output = "as_char"
footnote_backlink = "&#x21a9;&#xfe0e;"
toc_levels = "1..6"
smart_quotes = "lsquo,rsquo,ldquo,rdquo"
enable_coderay = false
